version: '3.8'

services:
  hacker-news-mcp:
    build: .
    # Uses the SSE transport from the Dockerfile CMD
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
      # Uncomment and set if needed
      # - HN_API_KEY=your_api_key
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
